version: '3.1'

services:
  pubsub_registry:
    build:
      context: .
      dockerfile: Dock.pubsub.Dockerfile
    command: ./bin/pubsub_registry foreground
    ports:
      - "4001:4001"
    volumes:
      - .:/opt/app
    environment:
      - MIX_ENV=prod
      - PORT=4001
