version: '3.1'

services:
  release:
    build:
      context: .
      dockerfile: Dock.smache-release.Dockerfile
    command: /bin/sleep 400
    ports:
      - "4000:4000"
    volumes:
      - .:/opt/app
    environment:
      - MIX_ENV=prod
      - PORT=4000
