version: "3.1"

services:
  uplink:
    image: registry.gitlab.com/selfup/smache:latest
    environment:
      - COOKIE=${COOKIE}
    command: ["./rel/boot.sh"]

  downlink:
    depends_on:
      - uplink
    links:
      - uplink
    image: registry.gitlab.com/selfup/smache:latest
    environment:
      - COOKIE=${COOKIE}
    command: ["./rel/boot.sh"]
